print('Lista Parte 1:''\n')
l = [1,2,3]
print('Append:')
l.append(4)
print(l)
print('Count:')
print(l.count(10))
print(l.count(2))
print('Extend:''\n')
print('append:')
x = [1,2,3]
x.append([4,5])
print(x)
print('extend:')
x = [1,2,3]
x.extend([4,5])
print(x)
print('Index:')
print(l.index(2))
#print(l.index(12))
print('Insert:')
l.insert(2,'inserted')
print(l)

print('\n''Lista Parte 2:')
print('Pop:')
popped = l.pop()
print(l)
print(popped)
print('Remove:')
l.remove('inserted')
print(l)
l = [1,2,3,4,3]
l.remove(3)
print(l)
print('Reverse:')
l.reverse()
print(l)
print('Sort:')
l.sort()
print(l)
