print('Sets Avançados parte 1:''\n')
s = set()
print('Add():')
s.add(1)
s.add(2)
print(s)
print('Clear():')
s.clear()
print(s)
print('Copy():')
s = {1,2,3}
sc = s.copy()
print(sc)
print(s)
s.add(4)
print(s)
print(sc)
print('Difference():')
print(s.difference(sc))
print('Difference_update():')
s1 = {1,2,3}
s2 = {1,4,5}
s1.difference_update(s2)
print(s1)
print('Discard():')
s.discard(2)
print(s)
print('Sets Avançados parte 2:''\n')
print('intersection():')
s1 = {1,2,3}
s2 = {1,2,4,5}
print(s1.intersection(s2))
print(s1)
print('intersection_update():')
s1.intersection_update(s2)
print(s1)
print('isdisjoint():')
s1 = {1,2,}
s2 = {1,2,4}
s3 = {5}
print(s1.isdisjoint(s2))
print(s1.isdisjoint(s3))
print('issubset():')
print(s1.issubset(s2))
print('issuperset():')
print(s2.issuperset(s1))
print('symmetric_difference():')
print(s1.symmetric_difference(s2))
print('union():')
print(s1.union(s2))
print('update():')
s1.update(s2)
print(s1)
