print('Hexadecimal:')
print(hex(246))
print(hex(512))
print('Binário:')
print(bin(1234))
print(bin(128))
print(bin(512))
print('função pow():')
print(pow(2,4))
print(pow(2,4,2))
print('Valor absoluto:')
print(abs(-3))
print(abs(3))
print('Round : reduz um número para uma precisão dada em digitos decimais:')
print(round(3.4))
print(round(3.1415926535, 2))
